---
- hosts: 127.0.0.1
  connection: local
  user: bryan
  sudo: True

  vars:
    ownhostname: one.hdp
    own_ip: 192.168.0.93
    ambarihostname: 192.168.0.93
    own_port: 44080
    src_dir: /Users/bryan/ansible
    ambari_tarball: ambari-2.2.0.0-centos6.tar.gz
    ambari_pkg: ambari-2.2.0.0
    hdp_utils_tarball: HDP-UTILS-1.1.0.20-centos6.tar.gz
    hdp_utils_pkg: HDP-UTILS-1.1.0.20
    hdp_tarball: HDP-2.3.4.0-centos6-rpm.tar.gz
    hdp_pgk: HDP-2.3.4.0
    nginx_webroot: /usr/share/nginx/html

  tasks:
    - name: Submit the blueprint
      command: curl -u admin:admin -H "X-Requested-By:ambari" -X POST http://{{ ambarihostname }}':'8080/api/v1/blueprints/bryce -d @blueprint.json

    - name: Update HDP repo
      command: curl -H "X-Requested-By:ambari" -u admin:admin -X PUT http://192.168.0.93':'8080/api/v1/stacks/HDP/versions/2.3/operating_systems/redhat6/repositories/HDP-2.3 -d @hdp.repo.json


    - name: Update HDP-UTILS repo
      command: curl -H "X-Requested-By:ambari" -u admin:admin -X PUT http://192.168.0.93':'8080/api/v1/stacks/HDP/versions/2.3/operating_systems/redhat6/repositories/HDP-UTILS-1.1.0.20 -d @hdp-utils.repo.json


    - name: Request blueprint installation
      command: curl -u admin:admin -H "X-Requested-By:ambari" -X POST http://{{ ambarihostname }}':'8080/api/v1/clusters/bryce -d @hostmapping.json

#    - name: Sleep
#      command: sleep 10

#    - name: Check status
#      command: curl -u admin:admin -H "X-Requested-By:ambari" -X POST http://{{ ambarihostname }}':'8080/api/v1/clusters/bryce/requests/1



